### ISSUE TITLE
setup container in docker-compose with environment variables

### ISSUE THREAD

**Issue by ghost** [ekristen/docker-openvpn-client#4]
Hello,

Is there a way I can start this container using docker compose environment variables?  How do I set these config options as stated in the readme?

`--config /vpn/client.conf --askpass /vpn/client.pwd --auth-nocache`

**Comment by raf924** [comment]
Welp this hasn't been answered by I'd like to know too.

**Comment by vincentbitter** [comment]
```
version: '2'

services:
  openvpn-client:
    container_name: openvpn-client
    image: ekristen/openvpn-client
    stdin_open: true
    tty: true
    command: --config /vpn/client.ovpn --askpass /vpn/client.pwd --auth-nocache
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - /data/vpn:/vpn
```
